# web/src/main/resources/application.yml  (default profile)
server:
  port: ${SERVER_PORT:8080}

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/scheduler}
    username: ${SPRING_DATASOURCE_USERNAME:scheduler}
    password: ${SPRING_DATASOURCE_PASSWORD:scheduler}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.jdbc.time_zone: UTC
  flyway:
    enabled: true
  quartz:
    job-store-type: jdbc
    properties:
      org.quartz.scheduler.instanceName: scheduler-platform
      org.quartz.jobStore.class: org.quartz.impl.jdbcjobstore.JobStoreTX
      org.quartz.jobStore.driverDelegateClass: org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
      org.quartz.jobStore.misfireThreshold: 60000
      org.quartz.threadPool.threadCount: 10

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

springdoc:
  swagger-ui:
    path: /swagger-ui
  api-docs:
    path: /v3/api-docs

logging:
  level:
    org.springframework: INFO
